import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'

export async function GET(request: NextRequest, { params }: { params: { id: string } }) {
  try {
    const session = await getServerSession(authOptions)
    if (!session || session.user.role !== 'ADMIN') {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }

    const { id } = params
    const report = await prisma.report.findUnique({ 
      where: { id },
      include: {
        user: {
          select: {
            name: true,
            email: true,
          }
        }
      }
    })
    
    if (!report) {
      return NextResponse.json({ error: 'Report not found' }, { status: 404 })
    }

    // Fetch the report data for PDF generation
    const reportPeriod = report.period
    const reportType = report.type

    // Create simple PDF with report metadata
    // For now, return a simple text file indicating the report
    // In production, you'd regenerate the PDF or fetch from a document storage service
    const reportContent = `
FINANCIAL CONTROL PANEL - ${reportType} REPORT
================================================

Period: ${reportPeriod}
Report ID: ${id}
Generated By: ${report.user.name} (${report.user.email})
Generated At: ${new Date(report.createdAt).toLocaleString()}

This is a placeholder. Full PDF generation would be done here.
    `.trim()

    return new NextResponse(reportContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="${id}.txt"`,
      }
    })
  } catch (err: any) {
    console.error('Report download error:', err)
    return NextResponse.json({ error: 'Internal server error', details: err.message }, { status: 500 })
  }
}
